version: '3.9'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: django_app
        command:
            bash -c "python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
        ports:
            - "8000:8000"
        restart: always
        env_file:
            - ./.env
        volumes:
            - .:/code
        depends_on:
            - db
            - redis
        networks:
            - app_network
    db:
        image: postgres:16
        container_name: postgres_db
        env_file:
            - ./.env
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app_network
    redis:
        image: redis:7
        container_name: redis
        ports:
            - "6379:6379"
        env_file:
            - ./.env
        volumes:
            - redis_data:/data
        networks:
            - app_network
    celery:
        build:
            context: .
        container_name: celery_worker
        command:
            celery -A config worker -l INFO
        env_file:
            - ./.env
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
        networks:
            - app_network

    celery_beat:
        build:
            context: .
        container_name: celery_beat
        command:
            celery -A config beat --loglevel=INFO
        env_file:
            - ./.env
        volumes:
            - .:/app
        depends_on:
            - db
            - redis
            - celery
        networks:
            - app_network
networks:
    app_network:
        driver: bridge
volumes:
    postgres_data:
    redis_data:
