# Generated by Django 5.1.7 on 2025-04-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_subscribe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribe",
            options={
                "verbose_name": "Подписка на курс",
                "verbose_name_plural": "Подписки на курсы",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Цена курса"
            ),
        ),
    ]
